[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
solc_version = "0.8.22"
gas_limit = 30000000

# Somnia Network Configuration
[rpc_endpoints]
somnia_testnet = "https://dream-rpc.somnia.network/"
somnia_mainnet = "https://api.infra.mainnet.somnia.network/"

[etherscan]
somnia_testnet = { key = "your-etherscan-api-key", url = "https://shannon-explorer.somnia.network/api" }
somnia_mainnet = { key = "your-etherscan-api-key", url = "https://explorer.somnia.network/api" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
